colortex0Format = RGBA16F
colortex1Format = RGBA16F
colortex2Format = RGBA16F
colortex3Format = RGBA16F
colortex4Format = RGBA16F
colortex5Format = RGBA16F
colortex6Format = RGBA16F
colortex7Format = RGBA16F
colortex8Format = RGBA16F
clear.colortex7=false
clear.colortex8=false
shadowMapResolution=4096
shadowDistance=120.0
shadowHardwareFiltering=false
sunPathRotation = 80.0
# 强制开启原版雨雪渲染
weather=true
# 15级高亮发光方块
block.10000=minecraft:glowstone minecraft:sea_lantern minecraft:shroomlight minecraft:jack_o_lantern minecraft:redstone_lamp minecraft:beacon minecraft:lava minecraft:end_portal minecraft:end_gateway minecraft:conduit minecraft:copper_bulb
# 10-14级中亮发光方块与小光源
block.10001=minecraft:torch minecraft:end_rod minecraft:nether_portal minecraft:soul_torch minecraft:soul_lantern minecraft:crying_obsidian

# ---- Water pass ---

blend.gbuffers_water = ONE ZERO ONE ZERO

# ---- Shader option screens ----
screen=<empty> <empty> <empty> <empty> [POST_PROCESSING] [COLOR_GRADING] [SSGI]
screen.POST_PROCESSING=FXAA EXPOSURE EXP_MIN EXP_MAX BLOOM_STRENGTH CROSS_BLUR_STRENGTH
screen.COLOR_GRADING=SATURATION LUMA_GAMMA WHITE_CLIP
screen.SSGI = SSGI_ENABLED SSGI_STRENGTH SSGI_SAMPLES SSGI_STEPS SSGI_RADIUS